server:
  port: 8080
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /ui
    #disable-swagger-default-url: true
    #urls:
    #  - name: api-gateway
    #    url: http://petstore.swagger.io/v2/swagger.json
    #  - name: id-center
    #    url: http://petstore.swagger.io/v2/swagger.json

spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  kafka:
    #    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
    consumer:
      group-id: "groupId"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "ru.mycomp.*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus